elfin_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - elfin_joint1
     - elfin_joint2
     - elfin_joint3
     - elfin_joint4
     - elfin_joint5
    #  - elfin_joint6
#   gains:
#       elfin_joint1: {p: 20.0, i: 0, d: 0.8, i_clamp_max: 0, i_clamp_min: 0, antiwindup: ture, publish_state: true }
#       elfin_joint2: {p: 20.0, i: 0, d: 0.8, i_clamp_max: 0, i_clamp_min: 0, antiwindup: ture, publish_state: true }
#       elfin_joint3: {p: 20.0, i: 0, d: 0.8, i_clamp_max: 0, i_clamp_min: 0, antiwindup: ture, publish_state: true }
#       elfin_joint4: {p: 20.0, i: 0, d: 0.8, i_clamp_max: 0, i_clamp_min: 0, antiwindup: ture, publish_state: true }
#       elfin_joint5: {p: 20.0, i: 0, d: 0.8, i_clamp_max: 0, i_clamp_min: 0, antiwindup: ture, publish_state: true }
#       elfin_joint6: {p: 20.0, i: 0, d: 0.8, i_clamp_max: 0, i_clamp_min: 0, antiwindup: ture, publish_state: true } 
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.1

  stop_trajectory_duration: 0.05
  state_publish_rate:  25
  action_monitor_rate: 10
elfin_arm_one_joint_controller:
  type: effort_controllers/JointEffortController
  joints: 
    - elfin_joint6
    
